function gnss = getNextGnss(lastUtcMillis, gnssRnx)
% GETNEXTGNSS returns a structure with the first observations received after the
% time lastUtcMillis

[nextIdx, ~, nextUtcMillis] = find(gnssRnx.utcMillis > lastUtcMillis, 1, 'first');
nextTow = gnssRnx.obs(nextIdx, 2);
gnss.obs = get_obs_vector(nextTow,           ...
    Config.CONSTELLATIONS,  ...
    Config.OBS_USED,        ...
    Config.OBS_COMBINATION, ...
    gnssRnx.obs,            ...
    gnssRnx.type);
gnss.utcMillis = nextUtcMillis;
gnss.tow = nextTow;
end